### ISSUE TITLE
DistributionBased missing from output folder

### ISSUE THREAD

**Issue by Anphisa** [delftdata/valentine-paper-results#13]
Hello everyone,
I think the output for the DistributionBased method is missing from the "output" folder. Or did I miss it somewhere?
Best,
Anphisa

**Comment by kPsarakis** [comment]
Hello! 

It is in the [CorrelationClustering.zip](https://github.com/delftdata/valentine-paper-results/blob/master/output/CorrelationClustering.zip) file.

**Comment by Anphisa** [comment]
Hello!

Thanks for the super-quick answer! I just re-downloaded the zip file and I can only see output for methods that have the prefix "CorrelationClustering" in there. Are you sure the DistributionBased results are in the folder? What are their names?

I counted the method names like this:

```
import os
folder_path = "XX\\CorrelationClustering"
file_names = []
for root, dirs, files in os.walk(folder_path, topdown=False):
    for name in files:
        if name.endswith(".json"):
            file_names.append(os.path.join(root, name))
            
method_names = []
for file_name in file_names:
    fn = file_names[0].split("\\")[-1]
    method_name = fn.split("__")[-1].split("{")[0]
    method_names.append(method_name)

from collections import Counter
Counter(method_names)
```

and it shows only "CorrelationClustering" method names.

**Comment by kPsarakis** [comment]
The `CorrelationClustering` is the same as the `DistributionBased` we changed the name later on but when we did the experiments, we had it as `CorrelationClustering`.

**Comment by Anphisa** [comment]
Ooh, thank you for the explanation! :)
